FROM apache/hive:4.0.1

USER root
RUN hdfs dfs -mkdir -p /user/hive/warehouse

# Instala wget y descarga el driver JDBC de MySQL
RUN apt-get update && \
    apt-get install -y default-mysql-client && \ 
    apt-get install -y wget && \
    wget -O /opt/hive/lib/mysql-connector-java.jar https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.0.33/mysql-connector-j-8.0.33.jar && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copia los archivos de configuración de Hive
COPY conf /opt/hive/conf

# Copia los scripts de inicialización
COPY scripts/init-hive.sh /docker-entrypoint-initdb.d/init-hive.sh
RUN chmod +x /docker-entrypoint-initdb.d/init-hive.sh

# Define las variables de entorno para Hive
ENV HIVE_HOME /opt/hive
ENV HIVE_CONF_DIR /opt/hive/conf
ENV HADOOP_HOME /opt/hadoop  # Asegúrate que esta ruta es correcta dentro de la imagen
ENV HADOOP_CONF_DIR /opt/hadoop/etc/hadoop # Asegúrate que esta ruta es correcta dentro de la imagen

# Elimina la versión antigua de SLF4J de Hadoop
RUN rm /opt/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar

# Expon los puertos (Metastore y HiveServer2)
EXPOSE 9083
EXPOSE 10000

# Usa el script init-hive.sh como punto de entrada
ENTRYPOINT ["/docker-entrypoint-initdb.d/init-hive.sh"]