FROM apache/hive:4.0.1

# Instala wget y descarga el driver JDBC de MySQL
RUN apt-get update && apt-get install -y wget && \
    wget -O /opt/hive/lib/mysql-connector-java.jar https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.33.jar && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copia los scripts de configuración
COPY conf /opt/hive/conf
COPY scripts/init-hive.sh /docker-entrypoint-initdb.d/init-hive.sh
